### ISSUE TITLE
Kommende nedlukning af Meetup-gruppen pga. admin-mangel

### ISSUE THREAD

**Issue by mikini** [kbhff/eggplant#141]
Fra https://www.meetup.com/Eggplant/messages/boards/thread/50550048

Fra meetup.com-email (Date: Thu, 26 Jan 2017 12:02:14 +0000 (UTC)):

"Nobody has stepped up yet to become the new Organizer of Eggplant open source development group. There are only 48 hours left before the group is shut down and removed from Meetup.com forever."

Jeg er med i Økologisk FødevareFællesskab Esbjerg (www.øffe.dk), og har primært fulgt med i udviklingen af Eggplant her på Meetup. Forventningen er at vi på sigt kan overgå til Eggplant, og være bedre kørende end med det ad-hoc hjemmeside og bestillingssystem vi anvender for nuværende.

Kunne der knyttes en kommentar til Meetup-gruppens tilstand fra nogle fra udviklergruppen? Er det et udtryk for at tingene sker andre steder end på meetup? Eller er det en del af det samlede billede af at der ikke sker meget i projektet for tiden?

Hilsner,
Mikkel

**Comment by tholype** [comment]
Hej Mikkel,

Der er stadig liv i projektet, men jeg kan ikke komme med en konkret status
i dag.

Der er har været tale om at droppe meetup fremadrettet, da annoncering her
flere gange alene giver besøg af personer, der ikke kan (eller vil)
programmere for os - men møder op med anden agenda (har selv kun oplevet
det en gang).

Andreas Lloyd har trukket sig som admin for gruppen. Benjamin har nu betalt
meetup for den næste måned og har gjort mig til co-organizer.

To be continued......    forhåbentlig snart,

Mange hilsner Thomas

2017-01-27 16:58 GMT+01:00 Mikkel Kirkgaard Nielsen <
notifications@github.com>:

**Comment by benjaoming** [comment]
> Kunne der knyttes en kommentar til Meetup-gruppens tilstand fra nogle fra udviklergruppen?

Set fra en udviklers synspunkt:

Meetup.com var en dårlig organiseringsform, da der kom alt for mange deltagere udefra, der ikke lagde et fast engagement, og meget ofte havde en meget ukonstruktiv effekt for afviklingen af Hackathons. En ting er at sætte nye folk i gang, en anden ting var al den løse snak -- så for et lignende projekt i fremtiden, bør man nok søge at igangsætte en fast arbejdsgruppe -- ikke den form for socialisering, som Meetup.com antyder.

Og helst med rigelig facilitering: Det er urealistisk (taler for mig selv) både at lægge frivillige udvikler-timer i sådan et projekt og samtidig skulle diske op med indpiskeriet til at holde det i live. Da det kørte godt, var det fordi der var facilitering, og da det kørte skidt, var det mangel på samme.

**Comment by tholype** [comment]
Hej Ben,

Godt at se et livstegn fra dig.    :)

Jeg er "her" også stadig. Jeg er stadig interesseret i at være med til  at
drive og facilitere et evt videre arbejde i eggplant -

Jeg er samtidig medlem af bestyrelsen for RØFF og kasserer for samme - og
jeg er bevidst om, at jeg ikke alene vil kunne drive en videre facilitering
af eggplant - der er nødt til at være mere end en person.

Vi snakkes ved,

Mange hilsner fra Thomas/ Roskilde / 53 64 46 37 / Thomas@RoskildeFF.dk /
tholype@gmail.com




2017-12-03 21:39 GMT+01:00 Benjamin Bach <notifications@github.com>:

**Comment by mikini** [comment]
Tak for status.
Var der ikke noget med at Køge FF skulle være prøveklud for EP? Blev det helt droppet?

Desværre har vi måttet opgive at basere fællesskabet i ØFFE i Esbjerg på at distribuere varer, det var for stort et arbejde for de få engagerede at organisere og drive i forhold til hvor mange der var interesserede i at aftage (helt uforståeligt med den kvalitet vi kunne skaffe). Håber det går bedre i de andre FF'er. Håber EP kan leve videre, har ikke lige pt. ressourcer til at bidrage yderligere.
