### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by valberg** [kbhff/eggplant#16]
It would be very nice if we could agree on a style guide. PEP8 is of course given in my opinion, but there are still some stuff that would be nice to get sorted out:
- Variable names: Personally I'm all for writing out names instead of contractions like `ctx` and `idx`, (an exception is `*args` and `**kwargs` since those are "a python thing")
- Argument layout: What to do when a function/method declaration/call gets over 80 characters? Personally I prefer one-argument-per-line like this:

```
    result = foo(
        bar,
        baz,
    )
```
- other?

**Comment by pawciobiel** [comment]
It's a matter of preference. How about we stop arguing if Easter is more important over Christmas?
IMHO if code is PEP8 and pylint isn't complaining too much than I can's see a strong reason not to accept it.

I vote :-1:

**Comment by benjaoming** [comment]
If PEP8 is a given, then I'm happy :)

I agree on the two other points, too... but if people don't do it, it doesn't bother me too much... it's more when things aren't PEP8.

I really hate unused imports and unused assignments, so if you have a code analyser that can detect these, please do use it :)

**Comment by benjaoming** [comment]
Could we maybe just say that we do PEP8, but we can't get into a longer discussion about things that aren't PEP8?

We can put our PEP8 rules in setup.cfg

**Comment by benjaoming** [comment]
So, basically we had a good consensus about PEP8, so this is enforced now in .travis builds!

Regarding other styles, we just have to try and get along... they can't be checked automatically anyways, so it's kind of hard to actually enforce a decision IMO.
