### ISSUE TITLE
Shut down "foodnet" heroku and fix domain on "eggplant" heroku

### ISSUE THREAD

**Issue by benjaoming** [kbhff/eggplant#28]
Sorry about assigning you :) But I kind of figure you have the keys and can do this in 2 minutes :)

**Comment by andreaslloyd** [comment]
Just for additional info: This is because when you send and invite at the current deployment (http://socialsquare-eggplant.herokuapp.com/ ), the invitation links to http://socialsquare-foodnet.herokuapp.com/ rather than http://socialsquare-eggplant.herokuapp.com

**Comment by benjaoming** [comment]
@pawciobiel just throwing an additional mention at you :)

**Comment by pawciobiel** [comment]
sure, no worries.
I think this is because Site was configured with domain 'socialsquare-foodnet.herokuapp.com'.
I'll have a look...

**Comment by andreaslloyd** [comment]
Yeah, I think we fixed that at the hackathon. But it's good to be sure. :-)
