### ISSUE TITLE
As a user I can see all products available for purchase

### ISSUE THREAD

**Issue by andreaslloyd** [kbhff/eggplant#52]
Each product has the product title, an photograph, a small description of it's content, it's price.
See mock-up here: https://foodnet.mybalsamiq.com/projects/foodnet/Web%20shop

**Comment by pawciobiel** [comment]
@andreaslloyd we need to think abut a place to store photograph images. If you still want to use heroku for hosting it may make sense to store those files in the cloud storage like Google Cloud Storage, Rackspace Files, Azure Storage or Amazon S3. We think it will be good if you will create and manage storage. Do you need any help with creating a storage for eggplant?

**Comment by benjaoming** [comment]
@pawciobiel this was discussed with @jambroo  while implementing a profile picture feature at the hackathon 2 weeks ago. We decided to use local storage for now, but with Django's storage backends, it should be possible to make the switch without any greater refactoring once we decide we wanna put an effort into that.

**Comment by pawciobiel** [comment]
@benjaoming the mockup from this ticket has user profile included and I wonder if I could use it but I can not see profile picture feature in the code, was this merged in?

**Comment by benjaoming** [comment]
It's something that @jambroo was working on, let's see what he says :)

**Comment by ghost** [comment]
Hi @benjaoming and @pawciobiel,
I started looking at this and got as far as allowing users to upload a profile picture. I will get it in sync with the current code base but wanted to right a test associated with it before making a pull request.

I was starting out with the facility to upload the profile picture and I was thinking putting it into the template could be a job for a future hackathon.
