### ISSUE TITLE
Write a "core definitions" guide

### ISSUE THREAD

**Issue by andreaslloyd** [kbhff/eggplant#73]
We need a shared reference for all developers – new and old – on the core definitions of the system. A simple diagram and a description of the core models of the system, how they relate to each other, and what they do in a easy-to-understand language.

No more than 2 pages that can bring new developers up to speed so that they can easily get started hacking on the system. :-)

**Comment by inflrscns** [comment]
This would be extremely helpful! :+1:

**Comment by benjaoming** [comment]
After the application refactor, the docs got left dangling, but I would suggest a chapter supporting this already existing chapter about software components:

http://eggplant.readthedocs.org/en/latest/dev/index.html#component-overview

**Comment by benjaoming** [comment]
If someone wants to write it but doesn't know how to do RST, I'd be happy to either help getting started or import someone's google doc (or similar).

**Comment by benjaoming** [comment]
Tagging as "wontfix" to note that we might close this issue because it seems unrealistic.

**Comment by benjaoming** [comment]
Actually, we already have a pretty okay component list (linked above), so let's just extend that...

Hoping that's okay with all...
