### ISSUE TITLE
Use CharField instead of SmallPosivitiveInteger

### ISSUE THREAD

**Issue by benjaoming** [kbhff/eggplant#75]
By popular demand, storing enum data in CharField is preferred. Like `UserProfile.sex` should be a CharField.

**Comment by ghost** [comment]
Hey Benjamin :)
Maybe I am missing something but UserProfile.sex is a CharField atm? I searched for SmallPositiveInteger in the codebase and couldn't find it too. Maybe they have been changed already?

**Comment by benjaoming** [comment]
Yeah actually I can confirm there are no more SmallPositiveIntegerFields left :) Well spotted!
